### ISSUE TITLE
Change the JS API to call different backends

### ISSUE THREAD

**Issue by wires** [typedefs/typedefs#104] opened 2019-01-18 15:20 UTC

**Comment by epost** [comment] 2019-02-28 22:07
The idea is that [ParserJS.idr](https://github.com/typedefs/typedefs/blob/98bf628abb94cc703d566ece2310c2e659a0fcda/parser.js/ParserJS.idr) call the various [Backend](https://github.com/typedefs/typedefs/tree/98bf628abb94cc703d566ece2310c2e659a0fcda/src/Backend)s instead of just the Haskell one.

**Comment by epost** [comment] 2019-02-28 22:15
Duplicate of #49

**Closed by epost** 2019-02-28 22:15 UTC
