### ISSUE TITLE
implement `weakenMu`

### ISSUE THREAD

**Issue by marcosh** [typedefs/typedefs#190] opened 2019-10-08 12:28 UTC
implement a function which allows to drop the context in `Mu` terms

**Comment by clayrat** [comment] 2019-10-08 15:14
To clarify, we need to extend the context instead of dropping it, i.e. a function of (approximate) type `Mu [] t -> Mu [...] (weaken t)`

**Comment by clayrat** [comment] 2019-10-08 21:00
It turns out to be an actual rabbit hole, the problem is that we need a signature like 
`weakenMu : {v : Vect n Type} -> Mu [] t -> Mu v (weakenTDef t (S n) (LTESucc LTEZero))`
which means you need to prove all kinds of nasty stuff about various ways of composing `Ty` and `weakenTDef`, e.g. proving properties of `rewrite` in the `TVar` case, and various ways of redistributing `weakenTDef` internally in recursive cases. 

However, if you have a concrete `t`, you can usually skip that and just reindex your structure naively. Maybe we could have a tactic for generating these weakenings?

**Comment by andrevidela** [comment] 2019-12-10 13:20
Is this still needed? Should we prioritise it for Statebox-core?

**Comment by andrevidela** [comment] 2019-12-10 14:23
Lets close this for now and re-open it if we run into it again

**Closed by andrevidela** 2019-12-10 14:23 UTC
